apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgres:13

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: study_manager

            - name: POSTGRES_USER
              value: study_manager

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: postgres-schema
              mountPath: /docker-entrypoint-initdb.d/schema.sql
              subPath: schema.sql
 
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-schema
          configMap:
            name: postgres-schema

        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc